services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: Aa123456
    restart: unless-stopped
    networks:
      - yg-net

networks:
  yg-net:
    external: true