<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPluginModule>true</IsPluginModule>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FastEndpoints" />
		<PackageReference Include="WolverineFx" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\YG.BuildingBlocks.Auth\YG.BuildingBlocks.Auth.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\YG.BuildingBlocks.Messaging\YG.BuildingBlocks.Messaging.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\YG.BuildingBlocks.Modules\YG.BuildingBlocks.Modules.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\YG.BuildingBlocks.Persistence\YG.BuildingBlocks.Persistence.csproj" />
		<ProjectReference Include="..\YG.Modules.Workflow.Contracts\YG.Modules.Workflow.Contracts.csproj" />
	</ItemGroup>

</Project>