<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPluginModule>true</IsPluginModule>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\YG.BuildingBlocks.Modules\YG.BuildingBlocks.Modules.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\YG.BuildingBlocks.Persistence\YG.BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

</Project>
