// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YG.Modules.Workflow.Domain.Definition;
using YG.Modules.Workflow.Persistence;

#nullable disable

namespace YG.Modules.Workflow.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260718121954_AddRuntimeTables")]
    partial class AddRuntimeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YG.Modules.Workflow.Domain.Runtime.WorkflowHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("instance-started | task-created | task-claimed | task-completed | instance-completed");

                    b.Property<string>("Actor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<JsonElement?>("Data")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StepId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("workflow_history", "workflow", t =>
                        {
                            t.HasComment("Append-only audit trail. Never updated, never deleted.");
                        });
                });

            modelBuilder.Entity("YG.Modules.Workflow.Domain.Runtime.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Opaque reference to a business entity in some module. Never a FK.");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, JsonElement>>("Context")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("Accumulated state, keyed by step id. Steps write it; transitions only read it.");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Running | Completed");

                    b.HasKey("Id");

                    b.HasIndex("BusinessKey");

                    b.HasIndex("Status");

                    b.ToTable("workflow_instances", "workflow", t =>
                        {
                            t.HasComment("Executions. Definition version is pinned at start and never changes.");
                        });
                });

            modelBuilder.Entity("YG.Modules.Workflow.Domain.Runtime.WorkflowStepInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, JsonElement>>("CapturedData")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Step id inside the pinned definition document.");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("workflow_step_instances", "workflow", t =>
                        {
                            t.HasComment("One row per activated step. captured_data is frozen once the step completes.");
                        });
                });

            modelBuilder.Entity("YG.Modules.Workflow.Domain.Runtime.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FormRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Opaque role name; holders see the task in their inbox.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Open | Claimed | Completed");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StepInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedBy");

                    b.HasIndex("InstanceId");

                    b.HasIndex("StepInstanceId");

                    b.HasIndex("Status", "Role");

                    b.ToTable("workflow_tasks", "workflow", t =>
                        {
                            t.HasComment("The inbox. Open tasks are visible to all role holders; claiming takes ownership.");
                        });
                });

            modelBuilder.Entity("YG.Modules.Workflow.Domain.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DefinitionDocument>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("The definition graph: steps, transitions, activities, form references.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Stable workflow identity across versions (kebab-case).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Draft | PendingApproval | Published");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("workflow_definitions", "workflow", t =>
                        {
                            t.HasComment("Designed workflow definitions. One row per version; Published rows are immutable.");
                        });
                });

            modelBuilder.Entity("YG.Modules.Workflow.Domain.Runtime.WorkflowHistoryEntry", b =>
                {
                    b.HasOne("YG.Modules.Workflow.Domain.Runtime.WorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YG.Modules.Workflow.Domain.Runtime.WorkflowStepInstance", b =>
                {
                    b.HasOne("YG.Modules.Workflow.Domain.Runtime.WorkflowInstance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("YG.Modules.Workflow.Domain.Runtime.WorkflowTask", b =>
                {
                    b.HasOne("YG.Modules.Workflow.Domain.Runtime.WorkflowInstance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YG.Modules.Workflow.Domain.Runtime.WorkflowStepInstance", "StepInstance")
                        .WithMany()
                        .HasForeignKey("StepInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("StepInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
